import Image from "next/image";
import Link from "next/link";
import type { Product } from "../data/products";
import { BFItSections } from "./BFitSections";

function Heading({ eyebrow, title, intro }: { eyebrow: string; title: string; intro?: string }) {
  return <div className="section-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{intro && <p>{intro}</p>}</div>;
}

export function ProductSections({ product, related }: { product: Product; related: Product[] }) {
  if (product.slug === "b-fit") return <BFItSections product={product} related={related} />;

  return <div className="product-sections">
    <section className="product-section situations" aria-labelledby="situations-title"><Heading eyebrow="Puede tener sentido si…" title="Empieza por lo que reconoces." intro="Cada rutina es distinta. Estas son algunas situaciones que pueden ayudarte a contextualizar la información del producto." /><div className="situation-grid">{product.needs.map((need, index) => <article className="situation-card" key={need}><span>{String(index + 1).padStart(2, "0")}</span><h3>{need}</h3></article>)}</div></section>
    <section className="product-section propose" aria-labelledby="propose-title"><div className="propose-intro"><p className="eyebrow">Qué propone</p><h2 id="propose-title">Una forma sencilla de integrarlo a tu día.</h2><p>{product.howItWorks || product.shortDescription}</p></div><div className="benefit-list">{product.benefits.map((benefit, index) => <div className="benefit-item" key={benefit}><span>{String(index + 1).padStart(2, "0")}</span><strong>{benefit}</strong></div>)}</div></section>
    {product.ingredients?.length ? <section className="product-section" aria-labelledby="ingredients-title"><Heading eyebrow="Ingredientes y componentes" title="Lo que forma parte de la fórmula." intro="Información presentada de forma simple, según los ingredientes disponibles en la ficha actual." /><div className="ingredient-grid">{product.ingredients.map((ingredient) => <article className="ingredient-card" key={ingredient.name}><div className="ingredient-icon" aria-hidden="true">✦</div><h3>{ingredient.name}</h3><p>{ingredient.description}</p></article>)}</div></section> : null}
    {product.usage?.length ? <section className="product-section usage-section" aria-labelledby="usage-title"><div className="usage-panel"><div><p className="eyebrow">Cómo integrarlo</p><h2 id="usage-title">Una rutina clara empieza por la etiqueta.</h2><p>Usa la presentación y la cantidad indicada por la etiqueta vigente. No modifiques la recomendación por inferencia.</p></div><ol className="usage-list">{product.usage.map((item, index) => <li key={item}><span>{index + 1}</span><p>{item}</p></li>)}</ol></div></section> : null}
    <section className="product-section expectation-section" aria-labelledby="expectation-title"><Heading eyebrow="Qué puedes esperar" title="Información para decidir con más claridad." intro="Los beneficios descritos son una forma de entender la propuesta del producto, no una promesa de resultados individuales." /><div className="expectation-grid">{product.benefits.slice(0, 3).map((benefit) => <article key={benefit}><span className="expectation-dot" aria-hidden="true"/><h3>{benefit}</h3></article>)}</div></section>
    {product.faq?.length ? <section className="product-section faq-section" aria-labelledby="faq-title"><Heading eyebrow="Preguntas frecuentes" title="Lo que normalmente te preguntas." /><div className="faq-list">{product.faq.map((item) => <details key={item.question}><summary>{item.question}<span aria-hidden="true">+</span></summary><p>{item.answer}</p></details>)}</div></section> : null}
    {product.warnings?.length ? <section className="product-section responsible-section" aria-labelledby="responsible-title"><div className="responsible-panel"><div className="responsible-badge" aria-hidden="true">i</div><div><p className="eyebrow">Uso responsable</p><h2 id="responsible-title">Ten presente antes de usarlo.</h2><p>{product.warnings.join(" ")}</p></div></div></section> : null}
    <section className="product-section related-section" aria-labelledby="related-title"><Heading eyebrow="Continúa explorando" title="También puede interesarte." /><div className="related-grid">{related.map((item) => <Link className="related-card" href={`/productos/${item.slug}`} key={item.slug} style={{ "--related-accent": item.theme.accent } as React.CSSProperties}><div><span className="eyebrow">{item.category}</span><h3>{item.name}</h3></div><Image src={item.catalogImage || item.productImage!} alt="" width={140} height={140} sizes="90px"/><span className="related-arrow" aria-hidden="true">↗</span></Link>)}</div></section>
    <section className="product-section product-closing"><div className="closing-card"><div><p className="eyebrow">¿Te interesa este producto?</p><h2>Consulta disponibilidad y precio con la persona que te compartió este catálogo.</h2></div><Link className="cta-main" href="/#productos">Volver al catálogo <span aria-hidden="true">→</span></Link></div><p className="product-disclaimer">{product.disclaimer}</p></section>
  </div>;
}
